CREATE TABLE cliente
(
    id       INT NOT NULL,
    nome     VARCHAR(255),
    cpf      VARCHAR(255),
    email    VARCHAR(255),
    telefone VARCHAR(255),
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

CREATE TABLE instituicao
(
    id_instituicao INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome           VARCHAR(255),
    cnpj           VARCHAR(255),
    CONSTRAINT pk_instituicao PRIMARY KEY (id_instituicao)
);

CREATE TABLE lance
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor      DOUBLE PRECISION,
    cliente_id INT,
    lote_id    INT,
    CONSTRAINT pk_lance PRIMARY KEY (id)
);

CREATE TABLE leilao
(
    id_leilao       INT NOT NULL,
    nome_leilao VARCHAR,
    data_ocorrencia date,
    data_visitacao  date,
    local           VARCHAR(255),
    endereco        VARCHAR(255),
    cidade          VARCHAR(255),
    estado          VARCHAR(255),
    status          VARCHAR(255),
    CONSTRAINT pk_leilao PRIMARY KEY (id_leilao)
);

CREATE TABLE leilao_instituicao
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_leilao      INT,
    id_instituicao INT,
    CONSTRAINT pk_leilaoinstituicao PRIMARY KEY (id)
);

CREATE TABLE lote
(
    id               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo             VARCHAR(255),
    nome             VARCHAR(255),
    descricao        VARCHAR(255),
    lance_inicial    DOUBLE PRECISION,
    leilao_id_leilao INT,
    CONSTRAINT pk_lote PRIMARY KEY (id)
);